#!/usr/bin/env bash
# Bash script that will display information about subdomains

# Function that displays information about subdomains
display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    record_type="$(dig +short -t A "$subdomain.$domain")"
    if [ -n "$record_type" ]; then
        echo "The subdomain $subdomain is a A record and points to $record_type"
    else
        echo "The subdomain $subdomain does not have an A record"
    fi
}

# Script logic
domain="$1"
subdomain="$2"

if [ -z "$domain" ]; then
    echo "Please provide a domain name."
    exit 1
fi

if [ -z "$subdomain" ]; then
    default_subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${default_subdomains[@]}"; do
        display_info "$domain" "$sub"
    done
else
    display_info "$domain" "$subdomain"
fi
