#!/usr/bin/env bash
# script that Install nginx web server

sudo apt-get update

sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo service nginx restart
