#!/usr/bin/env bash
# script that Install nginx web server

sudo apt-get update

sudo apt-get install -y nginx

cat <<<<EOF > /etc/nginx/sites-available/default
server{
listen 80;
location/{
echo "Hello World!";
}
}
EOF

service nginx restart
