#!/usr/bin/env bash
# Install nginx webserver and redirect

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i 's/listen 80;/listen 80 default_server;\n\n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com;\n    }/g' /etc/nginx/sites-available/default

sudo service nginx restart
