#!/usr/bin/env bash
# Install nginx web server and configure 301
sudo apt-get update
sudo apt-get -y install nginx

sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo sed -i '/server_name _;/a \\n        location /redirect_me {\n            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }\n' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
