#!/usr/bin/env bash
# install nginx webserver and redierect

sudo apt-get update
sudo apt-get -y install nginx

sudo sed -i 's/listen 80;/listen 80 default_server;\n\n    location \/redirect_me {\n        return 301 https:\/\/wughangar.tech\/another_page;\n    }/g' /etc/nginx/sites-available/default

sudo service nginx restart
