#!/usr/bin/env bash

# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom 404 page with the required content
echo "Ceci n'est pas une page." | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page for 404 errors
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /custom_404.html;|g' /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
sudo service nginx restart
