#!/usr/bin/env bash
# Update and install nginx
sudo apt-get update
sudo apt-get -y install nginx

echo "Ceci n'est pas une page.">/var/www/html/404.html

sudo sed -i '/server_name _;/a \\n        error_page 404 /404.html;\n' /etc/nginx/sites-available/default

sudo service nginx restart
