#!/usr/bin/env bash
# update and install nginx

sudo apt-get update
sudo apt-get -y install nginx

# declare variables
file="/etc/nginx/sites-available/default"
name="X-Served-By"
header="$(hostname)"

# ensure the file exists
if [ -f "$file" ]; then
    sudo sed -i "/server_name _;/a \ \n    add_header $name \"$header\";" "$file"
fi

# restarting server to apply changes
sudo systemctl nginx restart
