#!/usr/bin/env bash
# creating a custom nginx response header
# Update and install nginx
sudo apt update
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo sed -i '/server_name _;/a \\n        location /redirect_me {\n            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }\n' /etc/nginx/sites-available/default

# Create a custom HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom 404 page not found
sudo sed -i '/server_name _;/a \\n        error_page 404 /404.html;\n        location = /404.html {\n            internal;\n            return 404 "Ceci n'\''est pas une page.";\n        }' /etc/nginx/sites-available/default

# Define the custom header directly in the default configuration file
echo "location / {
   # adding custom response header
   add_header X-Served-By \$hostname;
}" | sudo sed -i '/server_name _;/a \\n' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
