#!/usr/bin/env bash
# creating a custom nginx response header
sudo apt update
sudo apt install -y nginx

# Define the custom header directly in the default configuration file
echo "location / {
   # adding custom response header
   add_header X-Served-By \$hostname;
}" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
