#!/usr/bin/env bash
# Installs HAProxy as a load balancer for two web servers

# Update and upgrade
apt-get -y update
apt-get -y upgrade

# Install HAProxy
apt-get -y install haproxy

# Define HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 18.234.105.167:80 check
    server web-02 100.25.222.179:80 check
"

# Append the configuration to haproxy.cfg
echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Create a backup of the original haproxy.cfg
cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Start the HAProxy service
sudo service haproxy start
