#!/usr/bin/env bash
# Installing haproxy server - latest version

# update and ugrade server if needed
apt-get -y update
apt-get -y upgrade

# Install latest haproxy
apt-get -y install haproxy=2.8.*

# haproxy configurations
configurations="\
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 34.207.190.83:80 check
    server web-02 52.91.178.39:80 check
"

# Add the configurations to .cfg
echo "$configurations" >> /etc/haproxy/haproxy.cfg

# enable init and start haproxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
