#!/usr/bin/env bash
#script that pings an ip adress passed an an arguement
if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ip_add="$1"
for ((i=1; i<=5; i++)); do
	ping -c 1 "$ip_add"
done
