#!/usr/bin/env bash
# Have docker container listen on port 80

apt install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
