#!/usr/bin/env bash
# Bash script to configure Nginx to listen on port 80 inside a Docker container

# Update and install nginx with flag -y for yes
apt install -y nginx

# Check configurations with flag -t
nginx -t

# Remove the default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to enable the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Configure nginx to listen to port 80 using sed -i 
sed -i 's/listen 80;/listen 80/' /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart

# Exit the container
exit
