#!/usr/bin/env bash
#script that echos a string when it receives a sigterm
function deal_sigterm
{
	echo "I am invincible!!!"
	exit 0
}

trap deal_sigterm SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
