#!/usr/bin/env bash
#script that displays numbers uisng while and case
x=1
while [[ $x -le 20 ]]
do
    case $x in
	    4)
		   echo "$x"
		  echo "bad luck from China"
		  ;;
	    9)
		    echo "$x"
		    echo "Bad luck from Japan"
		    ;;
	    17)
		    echo "$x"
		    echo "Bad luck from Italy"
		    ;;
	    *)
		    echo "$x"
		    ;;
	    esac
	    x=$((x + 1))
done
