#!/usr/bin/env bash
#script that displays the time for 12 hrs and 59 mins using while loop
hr=0
min=1

while [[ $hr -lt 13 ]]; do
	echo "Hour: $hr"
	while [[ $min -lt 60 ]]; do
		echo "$min"
		min=$((min + 1))
	done
	min=1
	hr=$((hr + 1))
done
