#!/usr/bin/env bash
# commands used to create and run docker container

sudo service apache2 start
netstat -tuln | grep 8080
docker run -p 8080:80 -d -it holbertonschool/265-0
curl localhost:8080
docker ps
docker logs 4acabfe69dca
docker logs 4acabfe69dca
docker exec it 4acabfe69dca /bin/bash
docker exec -it 4acabfe69dca /bin/bash
docker ps
curl 8080
ifconfig
docker logs
docker ps
docker logs 4acabfe69dca
docker exec -it 4acabfe69dca /bin/bash
curl localhost:8080
