#!/usr/bin/env bash
# script that runs nginx as nginx user and listens to port 8080

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/defaulit
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
